### ISSUE TITLE
Duplicate imports from RSS feed

### ISSUE THREAD

**Issue by davedodea** [vinkashq/discourse-autobot#5]
When setup to poll an RSS feed > to topic Id:
- duplicate posts will sometimes be added.
- at times, duplicates will be pulled one after another, other times the duplicates will appear more sporadically.

**Comment by schungx** [comment]
I find that whenever a feed is updated, the first item of last time is always recreated as a new post...

**Comment by vinothkannans** [comment]
Fixed here https://github.com/vinkashq/discourse-autobot/commit/9c5a71541a693da4c0f65a1f01a5e9b587a4b1f7
