### ISSUE TITLE
Stops after importing one item in category setup.

### ISSUE THREAD

**Issue by davedodea** [vinkashq/discourse-autobot#6]
When setup to import to a category: 
- an item is imported but that is all.
- importing stops after first import.

**Comment by schungx** [comment]
Same thing here.

**Comment by schungx** [comment]
I found the bug: https://meta.discourse.org/t/autobot-automatic-content-creator/71756/32

**Comment by vinothkannans** [comment]
Thank you 👍. A PR related to this issue is now Merged https://github.com/vinkashq/discourse-autobot/pull/8
